INSERT INTO challenge_templates (
    slug,
    grammar_topic,
    incorrect_template,
    correct_template,
    hint_template,
    slots_json,
    answer_variants_json,
    difficulty,
    weight,
    enabled,
    created_at,
    updated_at
) VALUES
('subject-verb-goes', 'subject-verb agreement', '{subject} go to {place} every {time_unit}.', '{subject} goes to {place} every {time_unit}.', 'Check the verb agreement.', '{"subject":["She","He","My brother"],"place":["school","the office","the gym"],"time_unit":["day","morning","weekend"]}', '["{subject} goes to {place} every {time_unit}."]', 1, 3, 1, NOW(), NOW()),
('plural-there-are', 'singular/plural agreement', 'There is {quantity} {item_plural} on the {surface}.', 'There are {quantity} {item_plural} on the {surface}.', 'Match the verb to the plural noun.', '{"quantity":["many","several","three"],"item_plural":["books","cups","boxes"],"surface":["table","desk","shelf"]}', '["There are {quantity} {item_plural} on the {surface}."]', 1, 3, 1, NOW(), NOW()),
('does-not-like', 'auxiliary verb choice', '{subject} do not like {thing}.', '{subject} does not like {thing}.', 'Use the correct auxiliary verb.', '{"subject":["He","She","My cousin"],"thing":["cold weather","spicy food","loud music"]}', '["{subject} doesn''t like {thing}."]', 1, 3, 1, NOW(), NOW()),
('have-eaten', 'past participles', 'I have ate my {meal} already.', 'I have eaten my {meal} already.', 'Check the past participle.', '{"meal":["lunch","dinner","breakfast"]}', '["I have already eaten my {meal}."]', 1, 3, 1, NOW(), NOW()),
('an-umbrella', 'article usage', '{subject} bought a umbrella before the {event}.', '{subject} bought an umbrella before the {event}.', 'Watch the article before a vowel sound.', '{"subject":["She","He","My aunt"],"event":["storm","meeting","parade"]}', '["{subject} bought an umbrella before the {event}."]', 1, 2, 1, NOW(), NOW()),
('arrived-at', 'prepositions', 'We arrived to the {place} at {time}.', 'We arrived at the {place} at {time}.', 'Check the preposition after arrived.', '{"place":["station","airport","hotel"],"time":["noon","sunset","nine"]}', '["We arrived at the {place} at {time}."]', 1, 2, 1, NOW(), NOW()),
('yesterday-went', 'simple tense consistency', 'Yesterday they goes to the {place}.', 'Yesterday they went to the {place}.', 'Use the past tense with yesterday.', '{"place":["museum","beach","market"]}', '["They went to the {place} yesterday."]', 1, 2, 1, NOW(), NOW()),
('baby-sleeps', 'subject-verb agreement', 'The baby sleep in the {place}.', 'The baby sleeps in the {place}.', 'Singular subjects need singular verbs.', '{"place":["crib","bedroom","stroller"]}', '["The baby sleeps in the {place}."]', 1, 2, 1, NOW(), NOW()),
('this-kind-is', 'singular/plural agreement', 'This kind of {item_plural} are expensive.', 'This kind of {item_plural} is expensive.', 'Match the verb to the subject kind.', '{"item_plural":["shoes","chairs","phones"]}', '["This kind of {item_plural} is expensive."]', 2, 1, 1, NOW(), NOW()),
('friends-were', 'subject-verb agreement', 'My friends was waiting outside the {place}.', 'My friends were waiting outside the {place}.', 'Plural subjects need plural verbs.', '{"place":["cinema","library","restaurant"]}', '["My friends were waiting outside the {place}."]', 1, 2, 1, NOW(), NOW()),
('good-at', 'prepositions', '{subject} is good in {subject_area}.', '{subject} is good at {subject_area}.', 'Use the usual preposition after good.', '{"subject":["She","He","My niece"],"subject_area":["math","science","art"]}', '["{subject} is good at {subject_area}."]', 1, 2, 1, NOW(), NOW()),
('a-university', 'article usage', 'He is an university student from {city}.', 'He is a university student from {city}.', 'Choose the article for the starting sound.', '{"city":["Sydney","Melbourne","Perth"]}', '["He is a university student from {city}."]', 2, 1, 1, NOW(), NOW()),
('have-written', 'past participles', 'They have wrote the {document}.', 'They have written the {document}.', 'Use the correct past participle.', '{"document":["report","email","proposal"]}', '["They have written the {document}."]', 1, 2, 1, NOW(), NOW()),
('does-like', 'auxiliary verb choice', 'Does your sister likes {activity}?', 'Does your sister like {activity}?', 'The main verb stays in base form after does.', '{"activity":["swimming","painting","running"]}', '["Does your sister like {activity}?"]', 2, 1, 1, NOW(), NOW()),
('news-is', 'singular/plural agreement', 'The news are surprising today.', 'The news is surprising today.', 'News takes a singular verb.', '{}', '["The news is surprising today."]', 2, 1, 1, NOW(), NOW()),
('were-watching', 'simple tense consistency', 'We were watch a movie when you called.', 'We were watching a movie when you called.', 'Use the -ing form after were.', '{}', '["We were watching a movie when you called."]', 2, 2, 1, NOW(), NOW()),
('depends-on', 'prepositions', 'He depends of his {relative} for advice.', 'He depends on his {relative} for advice.', 'Check the preposition after depends.', '{"relative":["brother","mother","uncle"]}', '["He depends on his {relative} for advice."]', 1, 2, 1, NOW(), NOW()),
('a-one-eyed', 'article usage', 'I saw an one-eyed cat near the {place}.', 'I saw a one-eyed cat near the {place}.', 'Choose the article for the spoken sound.', '{"place":["bakery","school","park"]}', '["I saw a one-eyed cat near the {place}."]', 3, 1, 1, NOW(), NOW()),
('each-has', 'subject-verb agreement', 'Each of the students have a {item}.', 'Each of the students has a {item}.', 'Each is singular.', '{"item":["locker","notebook","ticket"]}', '["Each of the students has a {item}."]', 2, 1, 1, NOW(), NOW()),
('has-driven', 'past participles', 'She has drove to the {place}.', 'She has driven to the {place}.', 'Use the past participle after has.', '{"place":["office","store","clinic"]}', '["She has driven to the {place}."]', 1, 2, 1, NOW(), NOW()),
('children-are', 'subject-verb agreement', 'The children is playing in the {place}.', 'The children are playing in the {place}.', 'Children is plural.', '{"place":["yard","park","hall"]}', '["The children are playing in the {place}."]', 1, 2, 1, NOW(), NOW()),
('a-house', 'article usage', 'They need an house near the {place}.', 'They need a house near the {place}.', 'Use the article that fits the initial sound.', '{"place":["station","school","hospital"]}', '["They need a house near the {place}."]', 1, 2, 1, NOW(), NOW()),
('discussed-topic', 'prepositions', 'We discussed about the {topic} yesterday.', 'We discussed the {topic} yesterday.', 'Discuss does not need about here.', '{"topic":["budget","schedule","plan"]}', '["Yesterday we discussed the {topic}."]', 2, 1, 1, NOW(), NOW()),
('did-not-go', 'simple tense consistency', 'He did not went to the {event}.', 'He did not go to the {event}.', 'Use the base verb after did not.', '{"event":["concert","meeting","festival"]}', '["He didn''t go to the {event}."]', 1, 3, 1, NOW(), NOW()),
('has-been-working', 'simple tense consistency', 'She has been work here since {year}.', 'She has been working here since {year}.', 'Use the -ing form after has been.', '{"year":["2020","last summer","January"]}', '["She has been working here since {year}."]', 2, 1, 1, NOW(), NOW()),
('fewer-apples', 'singular/plural agreement', 'There are less {item_plural} in this {container} now.', 'There are fewer {item_plural} in this {container} now.', 'Use fewer with countable nouns.', '{"item_plural":["apples","cookies","chairs"],"container":["basket","box","room"]}', '["There are fewer {item_plural} in this {container} now."]', 3, 1, 1, NOW(), NOW());
